<?php

use Sugarcrm\Sugarcrm\Console\CommandRegistry\CommandRegistry;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ClearAdditionalCacheCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ExportRecordsCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\MaintenanceOffCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\MaintenanceOnCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\OrphanedParentCleanupCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\OrphansCleanupCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\PruneBpmTablesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\PruneDatabaseCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildConfigCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildHtaccessCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildJsGroupingsCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildJsLanguagesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildRelationshipsCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildSchedulersCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildSpritesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildSugarLogicCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RebuildWorkflowCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RemoveXssCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RepairActivitiesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RepairAndRebuildCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RepairFieldCasingCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RepairInboundEmailCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RepairMissingTablesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RepairRolesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RepairTeamsCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportBlockedRecordCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportDropdownUsageCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportDuplicatesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportFieldUsageCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportLogicHooksCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportSchemaDiffCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportStaleBpmCasesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportStaleJourneysCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportStuckJobsCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\ReportTableSizesCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\RestoreRecordCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\SeedUsersCommand;
use Sugarcrm\Sugarcrm\custom\amaiza\SugarAdminCLI\Console\Command\UpgradeTeamsCommand;

// Register all SugarAdminCLI amaiza:admin:repair:* commands.
CommandRegistry::getInstance()->addCommands([
    new RepairAndRebuildCommand(),
    new UpgradeTeamsCommand(),
    new RebuildHtaccessCommand(),
    new RebuildConfigCommand(),
    new RebuildSugarLogicCommand(),
    new RebuildRelationshipsCommand(),
    new RebuildSchedulersCommand(),
    new RebuildWorkflowCommand(),
    new RebuildJsLanguagesCommand(),
    new RebuildJsGroupingsCommand(),
    new RebuildSpritesCommand(),
    new RepairFieldCasingCommand(),
    new RepairTeamsCommand(),
    new RepairRolesCommand(),
    new RepairInboundEmailCommand(),
    new RemoveXssCommand(),
    new RepairActivitiesCommand(),
    new SeedUsersCommand(),
    new ClearAdditionalCacheCommand(),
    new RestoreRecordCommand(),
    new OrphansCleanupCommand(),
    new MaintenanceOnCommand(),
    new MaintenanceOffCommand(),
    new PruneDatabaseCommand(),
    new RepairMissingTablesCommand(),
    new OrphanedParentCleanupCommand(),
    new ExportRecordsCommand(),
    new ReportBlockedRecordCommand(),
    new ReportStaleJourneysCommand(),
    new PruneBpmTablesCommand(),
    new ReportStaleBpmCasesCommand(),
    new ReportDuplicatesCommand(),
    new ReportLogicHooksCommand(),
    new ReportFieldUsageCommand(),
    new ReportDropdownUsageCommand(),
    new ReportSchemaDiffCommand(),
    new ReportTableSizesCommand(),
    new ReportStuckJobsCommand(),
]);
